spring:
  h2:
    console:
      enabled: true
      path: /h2-console
game:
  path:
    firstScenePath:  /view/start/start.fxml
    secondScenePath: /view/game/game.fxml
    thirdScenePath: /view/finish/finish.fxml
  view:
    welcomeLabel: Sprawdzian wiedzy o kosmosie
    startButton: START
