insert into QUESTION_MODEL values(1,'1248 km','10000 km','997 km','1550 km', 'Jaka srednice ma najwiekszy krater na Merkurym?')
insert into QUESTION_MODEL values(2,'100000 km','1000 km','239 000 km','270 000 km','Jaka srednice maja pierscienie saturna?')
insert into QUESTION_MODEL values(3,'9','Mniej','Wiecej','8','Ile planet jest w Ukladzie Slonecznym?')
insert into QUESTION_MODEL values(4,'Uran i Neptun','Wernus i Mars','Saturn i Uran','Mars i Jowisz','Pomiedzy jakimi dwoma planetami Ukladu Slonecznego znajduje sie pas planetoid?')
insert into QUESTION_MODEL values(5,'Mars','Ziemia','Slonce','Jowisz','Najwieksza planeta Ukladu Slonecznego to:')
insert into QUESTION_MODEL values(6,1959,1945,1979,1969,'W ktorym roku odbyla sie pierwsza zalogowa misja lotu na Ksiezyc?')
insert into QUESTION_MODEL values(7,'Rentgen','Appollo 11','Appolo 13','Luna','Jak nazywal sie pierwszy statek kosmiczny, ktory wyladowal na Ksiezycu?')
insert into QUESTION_MODEL values(8,'Gwiazda','Planeta','Kometa','Satelita','Czym jest Ksiezyc?')
insert into QUESTION_MODEL values(9,'24','12','6','4','Ile wyrozniamy glownych faz Ksiezyca?')
insert into QUESTION_MODEL values(10,'1410','1603','1490','1543','W ktorym roku Mikolaj Kopernik opublikowal swoje dzielo `O obrotach sfer niebieskich`?')
