insert into QUESTION_MODEL values(1,'1248 km','10000 km','997 km','1550 km', 'Jaka srednice ma najwiekszy krater na Merkurym?')
insert into QUESTION_MODEL values(2,'Jaka srednice maja pierscienie saturna?','100000 km','1000 km','239 000 km','270 000 km')
insert into QUESTION_MODEL values(3,'Ile planet jest w Ukladzie Slonecznym?','9','Mniej','Wiecej','8')
insert into QUESTION_MODEL values(4,'Pomiedzy jakimi dwoma planetami Ukladu Slonecznego znajduje sie pas planetoid?','Uran i Neptun','Wernus i Mars','Saturn i Uran','Mars i Jowisz')
insert into QUESTION_MODEL values(5,'Najwieksza planeta Ukladu Slonecznego to:','Mars','Ziemia','Slonce','Jowisz')
insert into QUESTION_MODEL values(6,'W ktorym roku odbyla sie pierwsza zalogowa misja lotu na Ksiezyc?',1959,1945,1979,1969)
insert into QUESTION_MODEL values(7,'Jak nazywal sie pierwszy statek kosmiczny, ktory wyladowal na Ksiezycu?','Rentgen','Appollo 11','Appolo 13','Luna')
insert into QUESTION_MODEL values(8,'Czym jest Ksiezyc?','Gwiazda','Planeta','Kometa','Satelita')
insert into QUESTION_MODEL values(9,'Ile wyrozniamy glownych faz Ksiezyca?','24','12','6','4')
insert into QUESTION_MODEL values(10,'W ktorym roku Mikolaj Kopernik opublikowal swoje dzielo `O obrotach sfer niebieskich`?','1410','1603','1490','1543')
